name: Deploy to AWS EC2

on:
  push:
    branches:
      - main # O pipeline roda sempre que houver um push na branch 'main'

env:
  # Substitua com o URI do seu ECR e o nome do repositório
  ECR_REGISTRY: 562419492190.dkr.ecr.us-east-2.amazonaws.com
  ECR_REPOSITORY: rtp-api
  IMAGE_TAG: ${{ github.sha }} # Usa o hash do commit como tag da imagem

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            # Navega para a pasta da aplicação no servidor
            cd /home/ec2-user/app

            # PASSO 1: Autentica o Docker do servidor no ECR
            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

            # PASSO 2: Baixa a nova imagem explicitamente
            docker pull ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

            # PASSO 3: Sobe a API com a nova imagem, forçando a recriação
            IMAGE_TAG=${{ env.IMAGE_TAG }} docker-compose up -d --force-recreate --no-deps rtp-api

            # ---- PASSO CRÍTICO ADICIONADO AQUI ----
            # Aguarda 10 segundos para garantir que a API tenha tempo de iniciar e se conectar ao banco
            echo "Aguardando a API iniciar antes de rodar as migrações..."
            sleep 10 

            # Executa as migrações dentro do container da API recém-criado
            echo "Rodando as migrações do banco de dados..."
            docker-compose exec rtp-api npm run migrate

            echo "Deploy concluído com sucesso!"

            # Limpa imagens antigas do servidor
            docker image prune -af
